pull_request_rules:
  - name: automatic merge
    conditions:
      - status-success=continuous-integration/travis-ci/pr
      - label!=merge-manually
    actions:
      merge:
        method: merge
        strict: true
